cmake_minimum_required(VERSION 3.21)
project(WuWaSteamVRReadOnlyCapture LANGUAGES CXX)
add_executable(steamvr-capture main.cpp)
set_property(TARGET steamvr-capture PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
target_compile_features(steamvr-capture PRIVATE cxx_std_20)
target_compile_options(steamvr-capture PRIVATE /EHsc)
target_include_directories(steamvr-capture PRIVATE ../../upstream/UEVR/dependencies/openvr/headers ../../upstream/UEVR/out/build/x64-RelWithDebInfo/_deps/json-src/include)
target_link_libraries(steamvr-capture PRIVATE d3d11 dxgi windowscodecs ole32)
add_executable(wuwa-recorder record.cpp)
set_property(TARGET wuwa-recorder PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
target_compile_features(wuwa-recorder PRIVATE cxx_std_20)
target_compile_options(wuwa-recorder PRIVATE /EHsc)
target_include_directories(wuwa-recorder PRIVATE ../../upstream/UEVR/dependencies/openvr/headers ../../upstream/UEVR/out/build/x64-RelWithDebInfo/_deps/json-src/include)
target_link_libraries(wuwa-recorder PRIVATE d3d11 d3dcompiler dxgi mfplat mfreadwrite mfuuid ole32)
enable_testing()
add_executable(capture-image-test test-image.cpp)
target_compile_features(capture-image-test PRIVATE cxx_std_20)
target_compile_options(capture-image-test PRIVATE /EHsc)
target_link_libraries(capture-image-test PRIVATE d3d11 windowscodecs ole32)
add_test(NAME capture-image COMMAND capture-image-test)
