// Original independent tooling: MIT. Uses marked only when regenerating pages.
const fs=require('node:fs'),path=require('node:path');
const {shell,escape,languageLinks}=require('./site-layout.cjs');
const root=path.resolve(__dirname,'..'),site=path.join(root,'site');
const candidates=[root,process.env.WUWA_NODE_MODULES,path.join(root,'dev-tools/node_modules'),path.join(process.env.USERPROFILE||process.env.HOME||'','.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules')].filter(Boolean);
(async()=>{
  const {marked}=await import(require('node:url').pathToFileURL(require.resolve('marked',{paths:candidates})).href);
  const links={'START-HERE.md':'guide.html#start','CONTROLS.md':'guide.html#controls','COMFORT.md':'guide.html#comfort',
    'TROUBLESHOOTING.md':'guide.html#recovery','NEXT-SESSION.md':'testing.html#next-test','CHECKPOINTS.md':'testing.html#checkpoints',
    'RELEASING.md':'credits.html#distribution','CREDITS.md':'credits.html','SUPPORT.md':'support.html','LICENSE.md':'license.html',
    'MIT.md':'license.html#mit','RISK.md':'risk.html','DISTRIBUTION-PLAN.md':'guide.html#packaging',
    'DEVELOPING.md':'developers.html','CONTRIBUTING.md':'developers.html#contributing'};
  function render(file,controls=false){
    let html=marked.parse(fs.readFileSync(path.join(root,file),'utf8').replace(/^# .+\r?\n/,''),{gfm:true});
    html=html.replace(/href="([^"#]+\.md)(#[^"]*)?"/g,(_,target,anchor)=>{
      if(/^https?:\/\//i.test(target))return 'href="'+target+(anchor||'')+'"';
      const next=links[path.basename(target)];if(!next)throw Error('Unmapped link '+target);
      return `href="${next}${anchor&&!next.includes('#')?anchor:''}"`;
    }).replace('href="site/support.html"','href="support.html"');
    html=html.replace(/<table>/g,'<div class="table-scroll"><table>').replace(/<\/table>/g,'</table></div>').replace(/<(\/?)h2>/g,'<$1h3>');
    if(controls)html=html.replace(/<tbody>([\s\S]*?)<\/tbody>/g,(_,body)=>'<tbody>'+body.replace(/<tr>/g,'<tr data-control-row>')+'</tbody>');
    return html;
  }
  const write=(file,title,description,body)=>fs.writeFileSync(path.join(site,file),shell(title,description,body));
  const risk=`<aside class="notice risk"><strong>Use at your own risk.</strong> This unofficial injector may be detected or blocked by anti-cheat; account restrictions or a ban are possible. It is not approved by Kuro Games. <a href="risk.html">Read the account-risk notice</a>.</aside>`;
  const png=file=>{const b=fs.readFileSync(path.join(site,file));if(b.toString('ascii',12,16)!=='IHDR')throw Error('Not a PNG: '+file);return {width:b.readUInt32BE(16),height:b.readUInt32BE(20)};};
  // Only owner-approved gameplay clips are shown; nothing appears until one exists.
  const privateProvenance=path.join(root,'release/media-provenance.json');
  const provenance=JSON.parse(fs.readFileSync(fs.existsSync(privateProvenance)?privateProvenance:path.join(root,'release/site-media.json'),'utf8'));
  // The public source export must regenerate without private capture paths.
  const publicMedia=(provenance.media||[]).filter(m=>m.kind==='gameplay-video'&&m.ownerApproved===true).map(m=>Object.fromEntries(['kind','ownerApproved','file','poster','caption','build','recorded','headset'].filter(k=>m[k]!==undefined).map(k=>[k,m[k]])));
  fs.writeFileSync(path.join(root,'release/site-media.json'),JSON.stringify({schema:1,media:publicMedia},null,2)+'\n');
  const video=(provenance.media||[]).filter(m=>m.kind==='gameplay-video'&&m.ownerApproved===true).map(c=>{
    if(!/^site\/media\/[\w.-]+\.(mp4|webm)$/.test(c.file||'')||!fs.existsSync(path.join(root,c.file)))throw Error('Approved clip is missing or misnamed: '+c.file);
    if(c.poster&&(!/^site\/media\/[\w.-]+\.(png|jpg)$/.test(c.poster)||!fs.existsSync(path.join(root,c.poster))))throw Error('Clip poster is missing: '+c.poster);
    for(const key of ['caption','build','recorded','headset'])if(!c[key])throw Error(`Approved clip needs "${key}": `+c.file);
    const src=c.file.slice(5);
    return `<figure><video controls preload="none"${c.poster?` poster="${escape(c.poster.slice(5))}"`:''}><source src="${escape(src)}" type="video/${src.endsWith('.webm')?'webm':'mp4'}"><a href="${escape(src)}">Download the gameplay clip</a></video><figcaption>${escape(c.caption)} Build: ${escape(c.build)}. Recorded ${escape(c.recorded)}, ${escape(c.headset)}.</figcaption></figure>`;
  }).join('');
  // Four real crops of the launcher page, one per numbered step, in order.
  const launcherSteps=[
    ['1-risk','Open <strong>WuWa VR Launcher.exe</strong> from the extracted folder. Read the account-risk notice and tick the box.','Launcher step 1, Account risk: the risk notice and a ticked box, I have read the account-risk notice and accept the risk.'],
    ['2-build','The current download contains the 26 Sep build. This earlier screenshot illustrates the build selector.','Earlier launcher example, Choose a build: Camera + acro checkpoint, 24 Sep 22:37 BST, above the Camera binding candidate, 25 Sep 22:49 BST. The current download contains one newer build with its own known-issues note.'],
    ['3-game','Use the standalone official launcher for the previously working route. Steam/Epic startup is experimental: Steam injection previously failed and has not been retested; Epic is untested. The 23:02 package reached gameplay via the standalone launcher on the owner’s PC.','Launcher step 3, How do you start the game: the official launcher is selected; manual Steam/Epic startup is marked experimental, with injection limitations explained.'],
    ['4-start','Start your headset software, then <strong>Apply &amp; launch</strong>. Accept the Windows permission prompt and press Play.','Launcher step 4, Start: Apply and launch, Check readiness and Apply without launching buttons, a note about the Windows permission prompt and a Ready message.']];
  const visualSteps=`<ol class="visual-steps">${launcherSteps.map(([id,text,alt])=>{const size=png(`media/launcher-step-${id}.png`);return `<li><figure><a href="media/launcher-step-${id}.png" aria-label="Open launcher step ${id[0]} at full size"><img src="media/launcher-step-${id}.png" width="${Math.round(size.width/2)}" height="${Math.round(size.height/2)}" loading="lazy" alt="${escape(alt)}"></a><figcaption>${text}</figcaption></figure></li>`;}).join('')}</ol><p class="small">Actual renders of the launcher page from the private test package, 25 September 2026, in a sample state. It runs only on your PC; your paths and status will differ.</p>`;
  // Show the pictures right after the numbered install steps they illustrate.
  const withVisualSteps=html=>{const next=html.replace(/(<h3>Install and launch<\/h3>[\s\S]*?<\/ol>)/,'$1'+visualSteps);if(next===html)throw Error('Setup needs an "Install and launch" list for the launcher pictures');return next;};
  const start=`<section id="get-started"><h2>How it starts</h2>${visualSteps}<p>In VR, <kbd>L3</kbd> + <kbd>R3</kbd> opens settings and <kbd>L3</kbd> + <kbd>Menu</kbd> shows the shortcut sheet. The beta is a portable ZIP: extract everything, then open WuWa VR Launcher.exe. <a href="guide.html#start">Full setup and removal steps</a>.</p></section>`;
  write('index.html','WuWa VR','Free unofficial WuWa VR fan project: captures, controller guide and known issues.',`<h1>WuWa VR</h1><p class="intro">A fan-made VR mod for Wuthering Waves on Windows, built on <a href="https://uevr.io/">praydog's UEVR</a>. Maintained by ChronoHaxx.</p><p><a class="button primary" href="https://github.com/ChronoHaxx/wuwa-vr/releases/download/beta-2026-09-26-230213/WuWa-VR-Launcher.zip">Download beta · Windows ZIP</a> <a href="https://github.com/ChronoHaxx/wuwa-vr/releases/tag/beta-2026-09-26-230213">Release notes &amp; source</a></p><p class="small">About 42 MB · complete portable app · all language fonts included</p><nav class="page-links" aria-label="Start here"><a href="guide.html">Player guide</a><a href="guide.html#recovery">Known issues</a><a href="feedback.html">Report a bug or request a feature</a></nav>${languageLinks()}${risk}
<section id="gameplay"><h2>See it in play</h2><p>Short clips from actual headset recordings. Choose a clip to play; nothing autoplays.</p><div class="feature-clips">${video}</div><details><summary>More stereo views</summary><figure><img src="media/rooftop-stereo.png" width="970" height="499" alt="Left and right eye views from a rooftop above the city at dusk."><figcaption>Rooftop, left and right eye. OpenXR Simulator, 24 September 2026. The HUD is on a separate layer and is not shown.</figcaption></figure><details><summary>Another view: the coast</summary><figure><img src="media/coast-stereo.png" width="970" height="499" loading="lazy" alt="Left and right eye views of a character beside the coast under a blue sky."><figcaption>Same build and capture method. ${video?'These are still images.':'These are still images; a gameplay video has not been recorded for this page yet.'}</figcaption></figure></details></details></section>
${start}
<section><h2>Current features</h2><ul><li><strong>Stereo VR and head tracking.</strong> Menus and HUD are usable in the saved playable build.</li><li><strong>Xbox controls and adjustable HUD.</strong> Show, hide or move the UI; open an in-VR shortcut sheet.</li><li><strong>First person.</strong> Keep the body visible with supported head bones hidden. Optional full-animation follow is more intense; comfort mode is available.</li><li><strong>Freecam, drone, plane and acro cameras.</strong> Experimental viewpoint controls; collision and comfort need more testing.</li><li><strong>Optional 6DOF window.</strong> Adapted from Elliott Tate's work.</li></ul><a href="guide.html#visual-controls">See the controller guide</a></section>
<section><h2>Known problems</h2><ul><li>Some NPC labels, speech bubbles and character materials appear in one eye only.</li><li>Character-preview reflections can appear twice per eye and move with the headset.</li><li>Full-animation first-person aiming remains unresolved. Newer camera, shadow and input changes still need headset checks.</li></ul><p>Keep <strong>Native Stereo Fix off</strong>. It previously caused SteamVR stutter. <a href="guide.html#recovery">Recovery steps</a>.</p></section>
<section><h2>Credits</h2><p>Built on work by praydog and the UEVR contributors, mirudo2, polar, SannpoKun, Indath, endlessfalls and Elliott Tate. <a href="credits.html">Contributions and licenses</a>.</p><p>Forks and improvements are welcome where the relevant licenses permit. Please keep community access free and credit the creators. Our original website and guides use MIT; this does not relicense the combined mod. <a href="license.html">License scope and sharing</a>.</p></section>`);
  const chapters=[['start','Setup','docs/START-HERE.md'],['controls','All Xbox shortcuts','docs/CONTROLS.md'],['comfort','HUD and camera comfort','docs/COMFORT.md'],['recovery','Problems and recovery','docs/TROUBLESHOOTING.md']];
  const filter='<div class="control-filter" hidden><label for="control-search">FIND A SHORTCUT</label><input id="control-search" type="search" placeholder="HUD, camera, acro, L3…" autocomplete="off"><button id="clear-search" class="reset-button" type="button">Clear</button></div><p id="control-count" role="status" aria-live="polite"></p>';
  const sheets=[['everyday','Everyday shortcuts','L3 + R3 opens settings; L3 + B shows or hides the game UI; L3 + A recenters; L3 + Menu toggles this sheet.'],['camera','Camera controls','The camera sheet changes with the active movement mode. This image shows Polar fly; the text reference below includes drone, plane and acro.'],['hud','HUD and mouse adjustment','Candidate builds: enable Xbox mouse shortcuts, close UEVR, press L3 + LB once and release. This image shows adjustment ON; press L3 + LB again for normal game controls. The 22:37 build uses the menu cursor or LB + R3 instead.'],['uevr','Using UEVR settings','Open UEVR with L3 + R3 first. Release RT, then use the D-pad and A; the left stick scrolls the focused pane.']];
  const visual=`<section id="visual-controls"><h2>Controller guide</h2><p>Actual renders of the supplied in-VR shortcut sheet, not game screenshots. The new HUD toggle is a candidate awaiting headset checks. Open an image at full size or use the searchable text below.</p>${sheets.map(([id,title,caption])=>`<figure><h3>${title}</h3><a href="media/shortcuts-${id}.png" aria-label="Open ${title.toLowerCase()} at full size"><img src="media/shortcuts-${id}.png" width="1600" height="900" loading="lazy" alt="${escape(title)}. ${escape(caption)}"></a><figcaption>${escape(caption)}</figcaption></figure>`).join('')}</section>`;
  const toc=[['start','Setup'],['visual-controls','Controller images'],...chapters.slice(1).map(([id,title])=>[id,title]),['packaging','Portable launcher']];
  write('guide.html','Player guide','Visual Xbox controls, setup, comfort and recovery for WuWa VR.',`<h1>Player guide</h1><p>Setup for the portable beta, illustrated controls and ways to recover when a setting feels wrong. <a href="languages.html">Getting started in 10 languages</a>.</p><button class="print-button" id="print-guide" type="button" hidden>Print / save this guide</button><div class="guide-grid"><nav class="toc" aria-label="Guide chapters">${toc.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}</nav><div class="guide-content">${chapters.map(([id,title,file],i)=>`<section id="${id}"><h2>${title}</h2>${id==='controls'?filter:''}${id==='start'?withVisualSteps(render(file)):render(file,id==='controls')}</section>${i===0?visual:''}`).join('')}<section id="packaging"><h2>Portable launcher</h2><p>The private test package is a ZIP with a folder and <strong>WuWa VR Launcher.exe</strong>. It needs no Python, terminal or GitHub account: it carries its own copy of Python and opens a page served only on your PC. Settings, backups and logs are kept in <code>%LOCALAPPDATA%\\WuWa VR Launcher</code>.</p><p>It is not a public release. The UEVR backend's upstream notice is "All rights reserved", so public downloads wait for permission. Game injection still needs Windows permission because the game runs as administrator. The launcher leaves game files alone. Use headset / Use simulator changes the global OpenXR runtime only when you click it, with the game and injector closed; Windows asks for permission. Use headset restores the previously saved runtime. Do not disable Windows security or anti-cheat. <a href="credits.html#distribution">Distribution status</a>.</p></section></div></div>`);
  write('testing.html','Local test notes','Local checkpoints and next-session comparisons; not public release acceptance.',`<h1>Local test notes</h1><p>For the prepared development installation. These notes do not establish public release or headset acceptance.</p><div class="guide-content"><section id="next-test"><h2>Next session</h2>${render('docs/NEXT-SESSION.md')}</section><section id="checkpoints"><h2>Checkpoint identities</h2>${render('docs/CHECKPOINTS.md')}</section></div>`);
  write('credits.html','Credits','Contributors and component-specific licensing.',`<h1>Credits</h1><div class="guide-content">${render('CREDITS.md')}<section id="distribution"><h2>Distribution status</h2><p>No public combined-mod binary is available yet. A private launcher package exists for local testing only; it keeps each component's notices and is not for re-sharing. Upstream redistribution permissions and a clean installation on another PC still need review. A scoped MIT license for our website and guides does not relicense the backend or game content.</p></section></div>`);
  // Read the maintained support text so the important disclaimer cannot drift.
  write('support.html','Optional support','Optional support for a spare-time hobby, without promised maintenance.',`<h1>Optional support</h1><div class="guide-content">${render('SUPPORT.md')}<p id="support-pending" class="notice">No payment details are collected on this site.</p><a id="support-link" class="button" rel="noopener noreferrer" hidden>Support the projects</a><p id="support-external" class="small" hidden>You will continue to an external payment provider. This website does not collect payment details.</p></div>`);
  write('risk.html','Account risk and disclaimer','Unofficial modification, anti-cheat and account restrictions.',`<h1>Account risk and disclaimer</h1><div class="guide-content">${render('docs/RISK.md')}</div>`);
  write('developers.html','Code and contributions','Source map, known rendering problems and ways to contribute to WuWa VR.',`<h1>Code and contributions</h1><nav class="page-links" aria-label="GitHub collaboration"><a data-project-link="code" hidden rel="noopener noreferrer">Browse GitHub</a><a data-project-link="fork" hidden rel="noopener noreferrer">Fork the repository</a><a data-project-link="issues" hidden rel="noopener noreferrer">Search issues</a><a href="feedback.html">Prepare a report</a></nav><p class="notice" data-repository-pending>The public repository has not been connected yet. The source map below explains the current review bundle; feedback drafts can still be copied.</p><div class="guide-content">${render('docs/DEVELOPING.md')}<section id="contributing"><h2>Contributing</h2>${render('CONTRIBUTING.md')}</section></div>`);
  require('./build-community.cjs');
  console.log('Generated simplified site, visual guide, risk/support pages and local test notes.');
})().catch(e=>{console.error(e);process.exitCode=1;});
