"""Configure owner-supplied public links locally; never creates or publishes accounts."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
KEYS = ("creator", "repositoryUrl", "supportUrl", "supportLabel")
MANAGED = "# Generated by dev/configure-sharing.py; owner-supplied destinations only.\n"


def read_config(file):
    text = file.read_text(encoding="utf-8-sig")
    result = {}
    for key in KEYS:
        match = re.search(r'^\s*"?' + re.escape(key) + r'"?\s*:\s*("(?:[^"\\]|\\.)*")', text, re.M)
        if not match:
            raise ValueError("Missing or non-literal configuration: " + key)
        result[key] = json.loads(match.group(1))
    return result


def repository_url(value):
    if not value:
        return ""
    parsed = urlsplit(value)
    if (parsed.scheme != "https" or parsed.netloc != "github.com" or parsed.query or parsed.fragment
            or not re.fullmatch(r"/[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?/[A-Za-z0-9_.-]+/?", parsed.path)):
        raise ValueError("Repository must be an exact https://github.com/OWNER/REPO URL")
    path = parsed.path.rstrip("/").removesuffix(".git")
    if path.rsplit("/", 1)[-1] in {"", ".", ".."}:
        raise ValueError("Repository name is empty or invalid")
    return "https://github.com" + path


def support_url(value):
    if not value:
        return ""
    parsed = urlsplit(value)
    if (parsed.scheme != "https" or not parsed.hostname or "." not in parsed.hostname
            or parsed.username or parsed.password or parsed.hostname.lower() == "localhost"):
        raise ValueError("Support must be the owner's public HTTPS payment-page URL")
    return value


def configure(root, *, repository=None, support=None, label=None, check=False):
    config_path = root / "site/config.js"
    config = read_config(config_path)
    if repository is not None:
        config["repositoryUrl"] = repository
    if support is not None:
        config["supportUrl"] = support
    if label is not None:
        if not label.strip() or len(label) > 100:
            raise ValueError("Use a short, nonempty support label")
        config["supportLabel"] = label.strip()
    config["repositoryUrl"] = repository_url(config["repositoryUrl"])
    config["supportUrl"] = support_url(config["supportUrl"])
    funding = root / ".github/FUNDING.yml"
    contacts = root / ".github/ISSUE_TEMPLATE/config.yml"
    # Preserve hand-edited funding and issue chooser files instead of overwriting them.
    for file in (funding, contacts):
        if file.exists():
            existing = file.read_text(encoding="utf-8-sig")
            if not existing.startswith(MANAGED) and existing.strip() != "blank_issues_enabled: true":
                raise ValueError("Existing manual file needs reconciliation: " + file.relative_to(root).as_posix())
    if not check:
        data = "// Owner-supplied public destinations. No accounts or payments are created here.\n"
        data += "window.WUWA_SITE = Object.freeze(" + json.dumps(config, indent=2, ensure_ascii=False) + ");\n"
        config_path.write_text(data, encoding="utf-8", newline="\n")
        funding.parent.mkdir(parents=True, exist_ok=True)
        funding.write_text(MANAGED + "custom: " + json.dumps([config["supportUrl"]] if config["supportUrl"] else []) + "\n", encoding="utf-8", newline="\n")
        contacts.parent.mkdir(parents=True, exist_ok=True)
        text = MANAGED + "blank_issues_enabled: true\n"
        if config["repositoryUrl"]:
            text += "contact_links:\n  - name: Known problems and recovery\n    url: "
            text += json.dumps(config["repositoryUrl"] + "/blob/HEAD/docs/TROUBLESHOOTING.md")
            text += "\n    about: Check the current rendering limits and recovery steps before filing a duplicate.\n"
        contacts.write_text(text, encoding="utf-8", newline="\n")
    return {"repositoryUrl": config["repositoryUrl"], "supportUrl": config["supportUrl"],
            "githubConfigured": bool(config["repositoryUrl"]), "supportConfigured": bool(config["supportUrl"]),
            "filesChanged": not check, "published": False}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", help="Confirmed GitHub repository URL; empty clears it")
    parser.add_argument("--support-url", help="Owner-supplied public support page; empty clears it")
    parser.add_argument("--support-label")
    parser.add_argument("--check", action="store_true", help="Validate and report without writing")
    args = parser.parse_args()
    try:
        print(json.dumps(configure(ROOT, repository=args.repository, support=args.support_url,
                                   label=args.support_label, check=args.check), indent=2))
    except ValueError as error:
        parser.exit(1, str(error) + "\n")


if __name__ == "__main__":
    main()
