// Original website layout. MIT; see LICENSE.md for the scope.
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const languages=[['en','English'],['zh-Hans','简体中文'],['ja','日本語'],['ko','한국어'],['es','Español'],['pt-BR','Português (Brasil)'],['fr','Français'],['de','Deutsch'],['ru','Русский'],['ar','العربية']];
function languageLinks(prefix=''){
  return `<details class="language-picker"><summary>Language / 语言 / اللغة</summary><nav aria-label="Languages">${languages.map(([code,name])=>`<a href="${prefix}l/${code}.html" lang="${code}" hreflang="${code}" dir="${code==='ar'?'rtl':'ltr'}" data-language="${code}">${name}</a>`).join('')}</nav></details>`;
}
function shell(title,description,body,{lang='en',dir='ltr',prefix='',labels={}}={}){
  const txt={guide:'Guide',feedback:'Feedback',credits:'Credits',language:'Languages',skip:'Skip to content',...labels};
  const community=`<a href="${prefix}developers.html" lang="en">Code &amp; contribute</a><a data-project-link="code" hidden rel="noopener noreferrer" lang="en">GitHub</a><a data-project-link="releases" hidden rel="noopener noreferrer" lang="en">Releases</a>`;
  return `<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#17191c"><title>${escape(title)} — WuWa VR</title><link rel="icon" href="${prefix}media/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}style.css"><script src="${prefix}config.js" defer></script><script src="${prefix}app.js" defer></script></head><body><a class="skip" href="#main">${escape(txt.skip)}</a><header class="header wrap"><a class="wordmark" href="${prefix}index.html" lang="en" dir="ltr">WuWa VR</a><nav aria-label="${escape(txt.guide)}"><a href="${lang==='en'?prefix+'guide.html':'#start'}">${escape(txt.guide)}</a><a href="${lang==='en'?prefix+'feedback.html':'#feedback'}">${escape(txt.feedback)}</a><a href="${prefix}credits.html">${escape(txt.credits)}</a><a href="${prefix}languages.html">${escape(txt.language)}</a></nav></header><main class="wrap" id="main">${body}</main><footer class="footer wrap"><p lang="en">Free, unofficial fan project. Not affiliated with Kuro Games.</p><nav aria-label="Project information" lang="en">${community}<a href="${prefix}risk.html">Account risk &amp; disclaimer</a><a href="${prefix}license.html">License scope</a><a href="${prefix}support.html">Optional support</a><a href="${prefix}credits.html">Credits</a></nav><p class="small" lang="en">Original independent website and guide work: MIT. Upstream components keep their own terms.</p></footer></body></html>\n`;
}
module.exports={shell,escape,languageLinks,languages};
